name: Run UI Tests

on:
  workflow_dispatch:
    inputs:
      browser:
        description: "Browser to run the tests on"
        required: true
        default: "chrome"  # Default value
        type: string
      environment:
        description: "Environment to run the tests (Test/Stage)"
        required: true
        default: "Test"
        type: string

jobs:
  ui-tests:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Install Chrome and dependencies
      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          sudo apt-get install -y xvfb

      # Step 3: Start Xvfb
      - name: Start Xvfb
        run: |
          export DISPLAY=:99
          Xvfb :99 -screen 0 1920x1080x16 &
          sleep 3

      # Step 4: Set up Java
      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Step 5: Cache Maven dependencies
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven

      # Step 6: Pass Inputs as Environment Variables
      - name: Set Environment Variables
        run: |
          echo "BROWSER=${{ github.event.inputs.browser }}" >> $GITHUB_ENV
          echo "ENVIRONMENT=${{ github.event.inputs.environment }}" >> $GITHUB_ENV

      # Step 7: Run Maven Tests with Parameters
      - name: Run UI Tests
        run: mvn test -Dbrowser=$BROWSER -Denvironment=$ENVIRONMENT
